# Generated by Django 5.1.2 on 2024-11-26 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapLines', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lines',
            name='inicio',
            field=models.TimeField(null=True),
        ),
        migrations.AddField(
            model_name='lines',
            name='termino',
            field=models.TimeField(null=True),
        ),
    ]
