/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package interfaces;

import conector.Conector;
import static interfaces.Motoristas.InserirIcone;
import java.awt.Toolkit;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author thale
 */
public class Onibus_Lista extends javax.swing.JFrame {

    /**
     * Creates new form Onibus_Lista
     */
    public Onibus_Lista() {
        initComponents();
        PopulaJTable();
        InserirIcone(this);
        PopulaJTable();
        btnEditar.setEnabled(false);
        btnRemover.setEnabled(false);
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtbOnibus = new javax.swing.JTable();
        btnEditar = new javax.swing.JButton();
        btnRemover = new javax.swing.JButton();
        txtID = new javax.swing.JTextField();
        txtPlaca = new javax.swing.JTextField();
        btnConcluido = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        CBEmpresa = new javax.swing.JComboBox<>();
        CBTipo = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Onibusca: Listar Ônibus");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel2.setText("ID");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel3.setText("Empresa");

        jtbOnibus.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jtbOnibus.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ID", "Placa", "Empresa", "Tipo"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jtbOnibus.getTableHeader().setReorderingAllowed(false);
        jtbOnibus.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtbOnibusMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jtbOnibus);

        btnEditar.setBackground(new java.awt.Color(60, 85, 79));
        btnEditar.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnEditar.setForeground(new java.awt.Color(255, 255, 255));
        btnEditar.setText("Editar");
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });

        btnRemover.setBackground(new java.awt.Color(60, 85, 79));
        btnRemover.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnRemover.setForeground(new java.awt.Color(255, 255, 255));
        btnRemover.setText("Remover");
        btnRemover.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRemoverActionPerformed(evt);
            }
        });

        txtID.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIDActionPerformed(evt);
            }
        });

        txtPlaca.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        btnConcluido.setBackground(new java.awt.Color(60, 85, 79));
        btnConcluido.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        btnConcluido.setForeground(new java.awt.Color(255, 255, 255));
        btnConcluido.setText("Concluído");
        btnConcluido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConcluidoActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setText("Placa");

        CBEmpresa.setFont(new java.awt.Font("Noto Sans", 0, 24)); // NOI18N

        CBTipo.setFont(new java.awt.Font("Noto Sans", 0, 24)); // NOI18N

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel4.setText("Tipo");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 565, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnEditar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(68, 68, 68)
                                .addComponent(btnRemover, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(txtID, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(txtPlaca)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(CBTipo, 0, 258, Short.MAX_VALUE)
                                    .addComponent(CBEmpresa, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(btnConcluido, javax.swing.GroupLayout.PREFERRED_SIZE, 512, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnEditar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnRemover, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addGap(2, 2, 2)
                .addComponent(txtID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addGap(4, 4, 4)
                .addComponent(txtPlaca, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(CBEmpresa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(CBTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(btnConcluido, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jtbOnibusMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtbOnibusMouseClicked
        PopulaEmpresas();
        PopulaTipo();
        int linha = jtbOnibus.getSelectedRow();
        txtID.setText(jtbOnibus.getValueAt(linha,0).toString());
        txtPlaca.setText(jtbOnibus.getValueAt(linha,1).toString());
        CBEmpresa.setSelectedItem(jtbOnibus.getValueAt(linha,2).toString());
        CBTipo.setSelectedItem(jtbOnibus.getValueAt(linha,3).toString());
        btnEditar.setEnabled(true);
        btnRemover.setEnabled(true);
        txtID.setEditable(false);
      
    }//GEN-LAST:event_jtbOnibusMouseClicked

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
            String strID = txtID.getText();
            String strPlaca = txtPlaca.getText();
            String id1 = getID1();
            String id2 = getID2();
            String sql = "update onibus set placa = ? , empresa_id = ? , tipo_id = ? where id = ? ";
        try {   
            Conector conector = new Conector();
            Connection con = conector.getConnection();
            PreparedStatement stm=null;
            stm = con.prepareStatement(sql);
            stm.setString(1, strPlaca);
            stm.setString(2, id1);
            stm.setString(3, id2);
            stm.setString(4, strID);
            stm.execute();
        } catch (SQLException ex) {
            Logger.getLogger(Motoristas_Lista.class.getName()).log(Level.SEVERE, null, ex);
        }
        clear();
        PopulaJTable();
    }//GEN-LAST:event_btnEditarActionPerformed

    private void btnRemoverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemoverActionPerformed
        String strID = txtID.getText();

        String sql = "delete from onibus where id= ?";
        Conector conector = new Conector();
        Connection con = conector.getConnection();
        PreparedStatement stm = null;
        try {
            stm= con.prepareStatement(sql);
            stm.setString(1, strID);
            stm.execute();
        } catch (SQLException ex) {
            Logger.getLogger(Motoristas_Lista.class.getName()).log(Level.SEVERE, null, ex);
        }
        clear();
        PopulaJTable();
        

    }//GEN-LAST:event_btnRemoverActionPerformed

    private void txtIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIDActionPerformed

    private void btnConcluidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConcluidoActionPerformed
        this.setVisible(false);
        Principal principal = new Principal();
        principal.setVisible(true);
    }//GEN-LAST:event_btnConcluidoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Onibus_Lista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Onibus_Lista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Onibus_Lista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Onibus_Lista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Onibus_Lista().setVisible(true);
            }
        });
    }
       private void PopulaJTable() {
        String sql = "select o.id, o.placa, e.nome as empresa, t.nome as tipo_oni from onibus o inner join empresa e on o.empresa_id = e.id inner join tipo_oni t on o.tipo_id = t.id;";
        Conector conector = new Conector();
        Connection con = conector.getConnection();
        try {
            PreparedStatement stm = con.prepareStatement(sql);
            ResultSet rs = stm.executeQuery();
            DefaultTableModel model = (DefaultTableModel) jtbOnibus.getModel();
            model.setNumRows(0);
            while (rs.next()) {
                model.addRow(new Object[]{
                        rs.getInt("id"),
                        rs.getString("placa"),
                        rs.getString("empresa"),
                        rs.getString("tipo_oni")
                });
            }
            stm.close();
            con.close();
        } catch (SQLException ex) {
            System.out.println(ex);
        }
    }
        private void PopulaEmpresas(){
      
        try {
            String sql = "select * from empresa";
            Conector conector = new Conector();
            Connection con = conector.getConnection();
            PreparedStatement stm = con.prepareStatement(sql);
            stm.execute();
            ResultSet rs = stm.executeQuery(sql);
            CBEmpresa.addItem("Selecione:");
            while (rs.next()){
            CBEmpresa.addItem(rs.getString("NOME"));
            }
            
        } catch (SQLException ex) {
            Logger.getLogger(Onibus.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }
    private void PopulaTipo(){
         try {
            String sql = "select * from tipo_oni";
            Conector conector = new Conector();
            Connection con = conector.getConnection();
            PreparedStatement stm = con.prepareStatement(sql);
            stm.execute();
            ResultSet rs = stm.executeQuery(sql);
            CBTipo.addItem("Selecione:");
            while (rs.next()){
            CBTipo.addItem(rs.getString("NOME"));
            }
            
        } catch (SQLException ex) {
            Logger.getLogger(Onibus.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
   private String getID1(){
    String strEmpresa = CBEmpresa.getSelectedItem().toString();
    String sql = "select ID from empresa where nome = ?";
    Conector conector = new Conector();
    Connection con = conector.getConnection();
    String id1 = null;
    try{

        PreparedStatement stm = con.prepareStatement(sql);
        stm.setString(1, strEmpresa);
        ResultSet rs = stm.executeQuery();
        if(rs.next()){
            id1 = rs.getString("id");
        }
        stm.close();
        con.close();
    }
    catch(SQLException ex){
        System.out.println(ex);
    }
    return id1;
   }
    private String getID2(){
        String strTipo = CBTipo.getSelectedItem().toString();
        String sql = "select id from tipo_oni where nome = ?";
        Conector conector = new Conector();
        Connection con = conector.getConnection();
        String id2 = null;
        try{
        PreparedStatement stm = con.prepareStatement(sql);
        stm.setString(1, strTipo);
        ResultSet rs = stm.executeQuery();
        if(rs.next()){
            id2 = rs.getString("id");
        }
        stm.close();
        con.close();
        } catch(SQLException ex){
            System.out.println(ex);
        }
       return id2; 
    }


    private void clear(){
        txtID.setText("");
        txtPlaca.setText("");
        CBEmpresa.setEditable(false);
        CBTipo.setEditable(false);
    }
      public static void InserirIcone(JFrame frm){
        try{
            frm.setIconImage(Toolkit.getDefaultToolkit().getImage("src/media/OniBusca.png"));
        }
        catch(Exception ex){
            System.out.println(ex.toString());
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> CBEmpresa;
    private javax.swing.JComboBox<String> CBTipo;
    private javax.swing.JButton btnConcluido;
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnRemover;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jtbOnibus;
    private javax.swing.JTextField txtID;
    private javax.swing.JTextField txtPlaca;
    // End of variables declaration//GEN-END:variables
}
