/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package interfaces;

import java.awt.Desktop;
import java.awt.Image;
import java.awt.Toolkit;
import java.io.IOException;
import java.net.URI;
import java.net.URISyntaxException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JLabel;

/**
 *
 * @author thale
 */

public class Principal extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
        setLocationRelativeTo(null);
        resize(img1,"src/media/principal.png");
        InserirIcone(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblNome = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        img1 = new javax.swing.JLabel();
        lblNome1 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        btnSair = new javax.swing.JMenu();
        btnLogout = new javax.swing.JMenuItem();
        userADD = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        UserList = new javax.swing.JMenuItem();
        MotorADD = new javax.swing.JMenu();
        inMoto = new javax.swing.JMenuItem();
        MotorList = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        busADD = new javax.swing.JMenuItem();
        BusList = new javax.swing.JMenuItem();
        btnAjuda = new javax.swing.JMenu();
        contatenos = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("OniBusca");
        setBackground(new java.awt.Color(255, 255, 255));
        setResizable(false);

        lblNome.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        lblNome.setForeground(new java.awt.Color(60, 85, 79));
        lblNome.setText("Administrador!");

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 26)); // NOI18N
        jLabel1.setText("Obrigado por escolher o OniBusca. ");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 26)); // NOI18N
        jLabel2.setText("Conosco, você pode gerenciar suas");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 26)); // NOI18N
        jLabel3.setText("oferecemos para otimizar sua ");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 26)); // NOI18N
        jLabel4.setText("linhas, motoristas e veículos com");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 26)); // NOI18N
        jLabel5.setText("facilidade e eficiência. Aproveite");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 26)); // NOI18N
        jLabel6.setText("também as funcionalidades que");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 26)); // NOI18N
        jLabel7.setText("operação e aumentar o lucro. Seja");

        lblNome1.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        lblNome1.setText("Olá, ");

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 26)); // NOI18N
        jLabel9.setText("bem-vindo a família OniBusca!");

        jMenuBar1.setBorder(null);
        jMenuBar1.setBorderPainted(false);
        jMenuBar1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N

        btnSair.setText("Administradores");

        btnLogout.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnLogout.setText("Sair");
        btnLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogoutActionPerformed(evt);
            }
        });
        btnSair.add(btnLogout);

        jMenuBar1.add(btnSair);

        userADD.setText("Usuários");

        jMenuItem2.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jMenuItem2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jMenuItem2.setText("Inserir Usuário");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        userADD.add(jMenuItem2);

        UserList.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_R, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        UserList.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        UserList.setText("Listar Usuários");
        UserList.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UserListActionPerformed(evt);
            }
        });
        userADD.add(UserList);

        jMenuBar1.add(userADD);

        MotorADD.setText("Motoristas");
        MotorADD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MotorADDActionPerformed(evt);
            }
        });

        inMoto.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        inMoto.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        inMoto.setText("Inserir Motorista");
        inMoto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inMotoActionPerformed(evt);
            }
        });
        MotorADD.add(inMoto);

        MotorList.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_R, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        MotorList.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        MotorList.setText("Listar Motoristas");
        MotorList.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MotorListActionPerformed(evt);
            }
        });
        MotorADD.add(MotorList);

        jMenuBar1.add(MotorADD);

        jMenu3.setBorder(null);
        jMenu3.setText("Ônibus");

        busADD.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        busADD.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        busADD.setText("Inserir ônibus");
        busADD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                busADDActionPerformed(evt);
            }
        });
        jMenu3.add(busADD);

        BusList.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_R, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        BusList.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        BusList.setText("Listar ônibus");
        BusList.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BusListActionPerformed(evt);
            }
        });
        jMenu3.add(BusList);

        jMenuBar1.add(jMenu3);

        btnAjuda.setText("Ajuda");
        btnAjuda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAjudaActionPerformed(evt);
            }
        });

        contatenos.setFont(new java.awt.Font("Noto Sans", 0, 18)); // NOI18N
        contatenos.setText("Contate-nos!");
        contatenos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                contatenosActionPerformed(evt);
            }
        });
        btnAjuda.add(contatenos);

        jMenuBar1.add(btnAjuda);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 410, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 410, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 410, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 410, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblNome1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblNome)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(img1, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNome1)
                    .addComponent(lblNome))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel9)
                .addContainerGap(24, Short.MAX_VALUE))
            .addComponent(img1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void UserListActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UserListActionPerformed
        Usuarios_Lista usuariolista = new Usuarios_Lista();
        usuariolista.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_UserListActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
       Usuarios Usuario = new Usuarios();
       Usuario.setVisible(true);
       this.setVisible(false);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void inMotoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inMotoActionPerformed
        Motoristas motoristas = new Motoristas();
        motoristas.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_inMotoActionPerformed

    private void btnAjudaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAjudaActionPerformed
        
    }//GEN-LAST:event_btnAjudaActionPerformed

    private void btnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutActionPerformed
         Login login = new Login();
         this.setVisible(false);
         login.setVisible(true);
         /*
          
         */
    }//GEN-LAST:event_btnLogoutActionPerformed

    private void MotorADDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MotorADDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MotorADDActionPerformed

    private void MotorListActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MotorListActionPerformed
        Motoristas_Lista motoristas_lista = new Motoristas_Lista();
        motoristas_lista.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_MotorListActionPerformed

    private void busADDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_busADDActionPerformed
        Onibus onibus = new Onibus();
        onibus.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_busADDActionPerformed

    private void BusListActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BusListActionPerformed
        Onibus_Lista onibuslista = new Onibus_Lista();
        onibuslista.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_BusListActionPerformed

    private void contatenosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_contatenosActionPerformed
        try {
            URI link = new URI("mailto:orkashield@gmail.com?subject=OniBusca:%20Suporte");
            Desktop.getDesktop().browse(link);
        } catch (URISyntaxException ex) {
            System.out.println(ex);
        } catch (IOException ex) {
            Logger.getLogger(Principal.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_contatenosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }
    public void resize(JLabel lblName, String url){
    ImageIcon icon = new ImageIcon(url);
    Image img = icon.getImage();
    Image imgScale = img.getScaledInstance(lblName.getWidth(), lblName.getHeight(), Image.SCALE_SMOOTH);
    ImageIcon scaledIcon = new ImageIcon(imgScale);
    lblName.setIcon(scaledIcon);
    }
    public static void InserirIcone(JFrame frm){
        try{
            frm.setIconImage(Toolkit.getDefaultToolkit().getImage("src/media/OniBusca.png"));
        }
        catch(Exception ex){
            System.out.println(ex.toString());
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem BusList;
    private javax.swing.JMenu MotorADD;
    private javax.swing.JMenuItem MotorList;
    private javax.swing.JMenuItem UserList;
    private javax.swing.JMenu btnAjuda;
    private javax.swing.JMenuItem btnLogout;
    private javax.swing.JMenu btnSair;
    private javax.swing.JMenuItem busADD;
    private javax.swing.JMenuItem contatenos;
    private javax.swing.JLabel img1;
    private javax.swing.JMenuItem inMoto;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JLabel lblNome;
    private javax.swing.JLabel lblNome1;
    private javax.swing.JMenu userADD;
    // End of variables declaration//GEN-END:variables
}
